name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker images
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/real-estate-react:latest -f ./web/Dockerfile ./web
        docker build -t ${{ secrets.DOCKER_USERNAME }}/real-estate-api:latest -f ./api/Dockerfile ./api
        docker push ${{ secrets.DOCKER_USERNAME }}/real-estate-react:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/real-estate-api:latest

    - name: Deploy to EC2
      env:
        EC2_USER: ${{ secrets.EC2_USER }}
        EC2_IP: ${{ secrets.EC2_IP }}
        EC2_KEY: ${{ secrets.EC2_KEY }}
      run: |
        echo "${EC2_KEY}" > ec2_key.pem
        chmod 600 ec2_key.pem
        ssh -i ec2_key.pem -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_IP }} << 'EOF'
          docker pull ${{ secrets.DOCKER_USERNAME }}/real-estate-react:latest
          docker pull ${{ secrets.DOCKER_USERNAME }}/real-estate-api:latest
          docker-compose -f /path/to/your/docker-compose.yml up -d --no-build
        EOF
