name: Frontend CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Docker
      run: |
        brew install docker
        brew install docker-machine-driver-vultr

    - name: Check Docker version
      run: docker --version; sleep 5;

    - name: Check Docker version
      run: open --background -a Docker


    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image for Web
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/real-estate-react:latest -f ./Dockerfile .
        docker push ${{ secrets.DOCKER_USERNAME }}/real-estate-react:latest

    - name: Deploy Web to EC2
      env:
        EC2_USER: ${{ secrets.EC2_USER }}
        EC2_IP: ${{ secrets.EC2_IP }}
        EC2_KEY: ${{ secrets.EC2_KEY }}
      run: |
        echo "${EC2_KEY}" > ec2_key.pem
        chmod 600 ec2_key.pem
        ssh -i ec2_key.pem -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_IP }} << 'EOF'
          docker pull ${{ secrets.DOCKER_USERNAME }}/real-estate-react:latest
          docker-compose -f /home/ec2-user/realestate-fullstack/docker-compose.yml up -d web --no-build
        EOF
